DROP TABLE IF EXISTS security_events;

CREATE TABLE security_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  public_id text,
  user_id uuid,
  login_history_id uuid,
  session_id uuid,
  refresh_token_id uuid,
  device_id text,
  audit_log_id uuid,
  event_code text NOT NULL,
  event_type text NOT NULL,
  severity text NOT NULL,
  status text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  source text NOT NULL,
  category text NOT NULL,
  ip_address text NOT NULL,
  browser text,
  operating_system text,
  device_type text,
  platform text,
  user_agent text,
  country text,
  state text,
  city text,
  latitude numeric,
  longitude numeric,
  risk_score integer DEFAULT 0,
  confidence_score integer DEFAULT 100,
  is_automated_response boolean DEFAULT false,
  response_action text,
  metadata jsonb,
  is_resolved boolean DEFAULT false,
  resolution_notes text,
  resolved_at timestamptz,
  resolved_by uuid,
  admin_action text,
  admin_notes text,
  actioned_at timestamptz,
  actioned_by uuid,
  is_deleted boolean DEFAULT false,
  deleted_at timestamptz,
  deleted_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  version integer DEFAULT 1
);
