DROP TABLE IF EXISTS public.sessions;

CREATE TABLE public.sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  public_id text,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  refresh_token_id uuid,
  device_id uuid,
  session_code text NOT NULL,
  session_status text NOT NULL,
  login_method text NOT NULL,
  login_time timestamptz NOT NULL,
  last_activity_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  idle_timeout_at timestamptz NOT NULL,
  logout_time timestamptz,
  logout_reason text,
  ip_address text,
  browser text,
  browser_version text,
  operating_system text,
  operating_system_version text,
  device_type text,
  device_model text,
  platform text,
  user_agent text,
  screen_resolution text,
  timezone text,
  language text,
  country text,
  state text,
  city text,
  latitude numeric,
  longitude numeric,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  version integer DEFAULT 1
);
