CREATE TABLE IF NOT EXISTS trusted_devices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  public_id text,
  user_id uuid REFERENCES users(id) ON DELETE CASCADE,
  device_code text,
  device_fingerprint text,
  device_name text,
  device_type text,
  platform text,
  browser text,
  browser_version text,
  operating_system text,
  operating_system_version text,
  manufacturer text,
  model text,
  screen_resolution text,
  language text,
  timezone text,
  ip_address text,
  mac_hash text,
  network_type text,
  first_country text,
  first_state text,
  first_city text,
  last_country text,
  last_state text,
  last_city text,
  first_login_at timestamptz DEFAULT now(),
  last_login_at timestamptz DEFAULT now(),
  last_activity_at timestamptz DEFAULT now(),
  total_logins integer DEFAULT 0,
  successful_logins integer DEFAULT 0,
  failed_logins integer DEFAULT 0,
  trust_status text DEFAULT 'PENDING',
  trusted_at timestamptz,
  revoked_at timestamptz,
  revoke_reason text,
  last_session_id uuid,
  last_refresh_token_id uuid,
  is_current_device boolean DEFAULT false,
  is_trusted boolean DEFAULT false,
  is_blocked boolean DEFAULT false,
  is_deleted boolean DEFAULT false,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  version integer DEFAULT 1
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  public_id text,
  user_id uuid REFERENCES users(id) ON DELETE CASCADE,
  session_id uuid,
  device_id uuid,
  token_hash text NOT NULL,
  jwt_id text NOT NULL,
  token_version integer DEFAULT 1,
  issued_at timestamptz DEFAULT now(),
  expires_at timestamptz NOT NULL,
  last_used_at timestamptz,
  revoked_at timestamptz,
  revoke_reason text,
  ip_address text,
  user_agent text,
  browser text,
  operating_system text,
  device_type text,
  platform text,
  country text,
  city text,
  is_revoked boolean DEFAULT false,
  is_expired boolean DEFAULT false,
  is_compromised boolean DEFAULT false,
  metadata jsonb,
  is_deleted boolean DEFAULT false,
  deleted_at timestamptz,
  deleted_by text,
  created_by text,
  updated_by text,
  version integer DEFAULT 1,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS otp_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  public_id text,
  user_id uuid,
  phone text,
  email text,
  otp_hash text,
  otp_length integer DEFAULT 6,
  purpose text,
  channel text,
  status text DEFAULT 'PENDING',
  request_ip text,
  request_device text,
  request_platform text,
  country_code text,
  expires_at timestamptz NOT NULL,
  verified_at timestamptz,
  resend_count integer DEFAULT 0,
  verification_attempts integer DEFAULT 0,
  max_attempts integer DEFAULT 3,
  max_resend_limit integer DEFAULT 3,
  failure_reason text,
  twilio_message_sid text,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  version integer DEFAULT 1
);

CREATE TABLE IF NOT EXISTS token_blacklist (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  token text NOT NULL,
  revoked_at timestamptz DEFAULT now()
);
