DROP TABLE IF EXISTS login_history;

CREATE TABLE login_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  public_id text,
  user_id uuid,
  session_id uuid,
  refresh_token_id uuid,
  device_id text,
  login_id text NOT NULL,
  login_type text NOT NULL,
  authentication_method text NOT NULL,
  login_status text NOT NULL,
  failure_reason text,
  otp_request_id text,
  ip_address text NOT NULL,
  browser text NOT NULL,
  browser_version text,
  operating_system text NOT NULL,
  operating_system_version text,
  device_type text NOT NULL,
  platform text NOT NULL,
  user_agent text NOT NULL,
  screen_resolution text,
  language text,
  timezone text,
  network_type text,
  internet_provider text,
  country text,
  state text,
  city text,
  latitude numeric,
  longitude numeric,
  login_time timestamptz NOT NULL DEFAULT now(),
  logout_time timestamptz,
  session_duration integer,
  risk_score integer DEFAULT 0,
  suspicious_reason text,
  is_trusted_device boolean DEFAULT false,
  is_successful boolean DEFAULT false,
  is_blocked boolean DEFAULT false,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  version integer DEFAULT 1
);
