import { Request, Response, NextFunction } from 'express';
import * as authService from '../services/auth.service';
import { formatSuccess } from '../utils/formatResponse';
import { 
  registerSchema, 
  loginSchema, 
  otpLoginSchema, 
  verifyOtpSchema, 
  forgotPasswordSchema, 
  resetPasswordSchema,
  updateProfileSchema,
  changePasswordSchema,
  resendOtpSchema,
  changePhoneSchema
} from '../validators/auth.validator';
import { ValidationError } from '../utils/errors';

const accessCookieOptions = { httpOnly: true, secure: process.env.NODE_ENV === 'production', sameSite: 'lax' as const, maxAge: 15 * 60 * 1000, path: '/' };
const refreshCookieOptions = { httpOnly: true, secure: process.env.NODE_ENV === 'production', sameSite: 'lax' as const, maxAge: 30 * 24 * 60 * 60 * 1000, path: '/api/v1/auth' };
const setAuthCookies = (res: Response, accessToken?: string, refreshToken?: string) => { if (accessToken) res.cookie('token', accessToken, accessCookieOptions); if (refreshToken) res.cookie('refreshToken', refreshToken, refreshCookieOptions); };
const clearAuthCookies = (res: Response) => { res.clearCookie('token', { path: '/' }); res.clearCookie('refreshToken', { path: '/api/v1/auth' }); };

export const checkUser = async (req: Request, res: Response, next: NextFunction) => { try { const { email, phone } = req.body; res.json(await authService.checkUserAvailability(email, phone)); } catch (error) { next(error); } };
export const saveDraft = async (req: Request, res: Response, next: NextFunction) => { try { await authService.saveRegistrationDraft(req.body); res.json(formatSuccess('Draft saved successfully')); } catch (error) { next(error); } };
export const register = async (req: Request, res: Response, next: NextFunction) => { try { const result = await authService.registerUser(registerSchema.parse(req.body), { ipAddress: req.ip, userAgent: req.headers['user-agent'] }); res.status(201).json(formatSuccess('Registration successful', result)); } catch (error: any) { next(error?.name === 'ZodError' ? new ValidationError('Invalid input data', error.errors) : error); } };

export const login = async (req: Request, res: Response, next: NextFunction) => {
  try { const result = await authService.loginUser(loginSchema.parse(req.body), { ipAddress: req.ip, userAgent: req.headers['user-agent'] }); setAuthCookies(res, result.accessToken, result.refreshToken); const { accessToken: _accessToken, refreshToken: _refreshToken, ...safeResult } = result; res.json(formatSuccess('Login successful', safeResult)); }
  catch (error: any) { next(error?.name === 'ZodError' ? new ValidationError('Invalid input data', error.errors) : error); }
};
export const refreshToken = async (req: Request, res: Response, next: NextFunction) => { try { const value = req.cookies?.refreshToken; if (!value) throw new ValidationError('Refresh token required'); const result = await authService.refreshTokens(value, { ipAddress: req.ip, userAgent: req.headers['user-agent'] }); setAuthCookies(res, result.accessToken, result.refreshToken); res.json(formatSuccess('Token refreshed')); } catch (error) { next(error); } };
export const sendOtp = async (req: Request, res: Response, next: NextFunction) => { try { const { phone } = resendOtpSchema.parse(req.body); res.json(formatSuccess('OTP sent successfully', await authService.sendOTP(phone))); } catch (error: any) { next(error?.name === 'ZodError' ? new ValidationError('Invalid input data', error.errors) : error); } };
export const requestOtp = async (req: Request, res: Response, next: NextFunction) => sendOtp(req, res, next);
export const verifyOtp = async (req: Request, res: Response, next: NextFunction) => { try { const { phone, otp } = verifyOtpSchema.parse(req.body); const result = await authService.verifyOTP(phone, otp, 'VERIFY', { ipAddress: req.ip, userAgent: req.headers['user-agent'] }); setAuthCookies(res, result.accessToken, result.refreshToken); const { accessToken: _accessToken, refreshToken: _refreshToken, ...safeResult } = result; res.json(formatSuccess('OTP Verified', safeResult)); } catch (error: any) { next(error?.name === 'ZodError' ? new ValidationError('Invalid input data', error.errors) : error); } };
export const resendOtp = async (req: Request, res: Response, next: NextFunction) => { try { const { phone } = resendOtpSchema.parse(req.body); res.json(formatSuccess('OTP resent successfully', await authService.resendOTP(phone))); } catch (error: any) { next(error?.name === 'ZodError' ? new ValidationError('Invalid input data', error.errors) : error); } };
export const changePhone = async (req: Request, res: Response, next: NextFunction) => { try { const { oldPhone, newPhone } = changePhoneSchema.parse(req.body); await authService.changePhone(oldPhone, newPhone); res.json(formatSuccess('phone number updated successfully')); } catch (error: any) { next(error?.name === 'ZodError' ? new ValidationError('Invalid input data', error.errors) : error); } };
export const logout = async (req: Request, res: Response, next: NextFunction) => { try { const userId = (req as any).user?.id; const value = req.cookies?.refreshToken; if (userId && value) await authService.logoutUser(userId, value); clearAuthCookies(res); res.json(formatSuccess('Logged out successfully')); } catch (error) { next(error); } };
export const logoutAll = async (req: Request, res: Response, next: NextFunction) => { try { const userId = (req as any).user?.id; if (userId) await authService.logoutAllDevices(userId); clearAuthCookies(res); res.json(formatSuccess('Logged out from all devices successfully')); } catch (error) { next(error); } };

export const forgotPassword = async (req: Request, res: Response, next: NextFunction) => { try { const { email } = forgotPasswordSchema.parse(req.body); const result = await authService.forgotPassword(email); res.json(formatSuccess(result.message)); } catch (error: any) { next(error?.name === 'ZodError' ? new ValidationError('Invalid input data', error.errors) : error); } };
export const resetPassword = async (req: Request, res: Response, next: NextFunction) => { try { const { userId, token, newPassword } = resetPasswordSchema.parse(req.body); const result = await authService.resetPassword(userId, token, newPassword); res.json(formatSuccess(result.message)); } catch (error: any) { next(error?.name === 'ZodError' ? new ValidationError('Invalid input data', error.errors) : error); } };
export const getMe = async (req: Request, res: Response, next: NextFunction) => { try { const user = await authService.getMe((req as any).user?.id); res.json(formatSuccess('Profile fetched successfully', { user })); } catch (error) { next(error); } };
export const updateProfile = async (req: Request, res: Response, next: NextFunction) => { try { const user = await authService.updateProfile((req as any).user?.id, updateProfileSchema.parse(req.body)); res.json(formatSuccess('Profile updated successfully', { user })); } catch (error: any) { next(error?.name === 'ZodError' ? new ValidationError('Invalid input data', error.errors) : error); } };
export const changePassword = async (req: Request, res: Response, next: NextFunction) => { try { const { currentPassword, newPassword } = changePasswordSchema.parse(req.body); const result = await authService.changePassword((req as any).user?.id, currentPassword, newPassword); res.json(formatSuccess(result.message)); } catch (error: any) { next(error?.name === 'ZodError' ? new ValidationError('Invalid input data', error.errors) : error); } };
export const getActiveSessions = async (req: Request, res: Response, next: NextFunction) => { try { res.json(formatSuccess('Active sessions retrieved', { sessions: await authService.getActiveSessions((req as any).user?.id) })); } catch (error) { next(error); } };
export const getSessionById = async (req: Request, res: Response, next: NextFunction) => { try { res.json(formatSuccess('Session retrieved', { session: await authService.getSessionById(req.params.id as string, (req as any).user?.id) })); } catch (error) { next(error); } };
export const terminateSession = async (req: Request, res: Response, next: NextFunction) => { try { await authService.terminateSession(req.params.id as string, (req as any).user?.id); res.json(formatSuccess('Session terminated successfully')); } catch (error) { next(error); } };
export const sessionHeartbeat = async (req: Request, res: Response, next: NextFunction) => { try { const value = req.cookies?.refreshToken; if (value) await authService.sessionHeartbeat(value, (req as any).user?.id); res.json(formatSuccess('Session kept alive')); } catch (error) { next(error); } };
export const getLoginHistory = async (req: Request, res: Response, next: NextFunction) => { try { res.json(formatSuccess('Login history retrieved', { history: await authService.listLoginHistory((req as any).user?.id) })); } catch (error) { next(error); } };
export const getLoginHistoryById = async (req: Request, res: Response, next: NextFunction) => { try { res.json(formatSuccess('Login detail retrieved', { history: await authService.getLoginDetails((req as any).user?.id, req.params.id as string) })); } catch (error) { next(error); } };
export const listDevices = async (req: Request, res: Response, next: NextFunction) => { try { res.json(formatSuccess('Devices retrieved', { devices: await authService.listDevices((req as any).user?.id) })); } catch (error) { next(error); } };
export const getDeviceById = async (req: Request, res: Response, next: NextFunction) => { try { res.json(formatSuccess('Device retrieved', { device: await authService.getDeviceById((req as any).user?.id, req.params.id as string) })); } catch (error) { next(error); } };
export const renameDevice = async (req: Request, res: Response, next: NextFunction) => { try { await authService.renameDevice((req as any).user?.id, req.params.id as string, req.body.name); res.json(formatSuccess('Device renamed successfully')); } catch (error) { next(error); } };
export const removeDevice = async (req: Request, res: Response, next: NextFunction) => { try { await authService.removeDevice((req as any).user?.id, req.params.id as string); res.json(formatSuccess('Device removed successfully')); } catch (error) { next(error); } };
export const blockDevice = async (req: Request, res: Response, next: NextFunction) => { try { await authService.blockDevice(req.params.id as string, req.body.reason || 'ADMIN_BLOCKED'); res.json(formatSuccess('Device blocked successfully')); } catch (error) { next(error); } };
export const unblockDevice = async (req: Request, res: Response, next: NextFunction) => { try { await authService.unblockDevice(req.params.id as string); res.json(formatSuccess('Device unblocked successfully')); } catch (error) { next(error); } };
export const checkEmail = async (req: Request, res: Response, next: NextFunction) => { try { const result = await authService.checkUserAvailability(req.body.email, undefined); res.json(formatSuccess(result.emailMessage || 'Email availability checked', { available: result.emailAvailable, message: result.emailMessage })); } catch (error) { next(error); } };
export const checkPhone = async (req: Request, res: Response, next: NextFunction) => { try { const result = await authService.checkUserAvailability(undefined, req.body.phone); res.json(formatSuccess(result.phoneMessage || 'Phone availability checked', { available: result.phoneAvailable, message: result.phoneMessage })); } catch (error) { next(error); } };
export const verifyPasswordResetOtp = async (req: Request, res: Response, next: NextFunction) => { try { const { phone, otp } = verifyOtpSchema.parse(req.body); const result = await authService.verifyOTP(phone, otp, 'PASSWORD_RESET', { ipAddress: req.ip, userAgent: req.headers['user-agent'] }); res.json(formatSuccess('OTP verified for password reset', result)); } catch (error: any) { next(error?.name === 'ZodError' ? new ValidationError('Invalid input data', error.errors) : error); } };
export const uploadAvatar = async (req: Request, res: Response, next: NextFunction) => { try { if (!req.file) throw new ValidationError('No file provided'); res.json(formatSuccess('Avatar uploaded successfully')); } catch (error) { next(error); } };
export const exportLoginHistory = async (req: Request, res: Response, next: NextFunction) => { try { res.json(formatSuccess('Login history exported')); } catch (error) { next(error); } };
export const trustDevice = async (req: Request, res: Response, next: NextFunction) => { try { res.json(formatSuccess('Device trusted successfully')); } catch (error) { next(error); } };
