import { Router, Response, NextFunction } from 'express';
import { authenticate, AuthRequest } from '../middleware';
import { supabase } from '../config/supabase';
import { ingestDocument, searchKnowledge } from '../services/rag.service';
import { analyzeDocument, detectCropDisease, generateGroundedResponse, transcribeAudio, translateText } from '../services/gemini.service';
import { createApiError } from '../middleware';

const router = Router();
router.use(authenticate);
const requireText = (value: unknown, field: string): string => { if (typeof value !== 'string' || !value.trim()) throw createApiError(400, `${field} is required`); return value.trim(); };
const parseDataUrl = (value: string) => { const match = value.match(/^data:([^;]+);base64,(.+)$/); return match ? { mimeType: match[1], data: match[2] } : { mimeType: 'image/jpeg', data: value }; };
const toCamel = (obj: unknown): unknown => Array.isArray(obj) ? obj.map(toCamel) : obj && typeof obj === 'object' && !(obj instanceof Date) ? Object.entries(obj).reduce<Record<string, unknown>>((r,[k,v]) => { r[k.replace(/_([a-z])/g, (_,c:string)=>c.toUpperCase())]=toCamel(v); return r; }, {}) : obj;

router.get('/history', async (req: AuthRequest,res: Response,next: NextFunction)=>{ try { const {data,error}=await supabase.from('ai_conversations').select('*, ai_messages(*)').eq('farmer_id',req.user!.id).order('updated_at',{ascending:false}); if(error) throw error; res.json({success:true,data:{conversations:toCamel(data)}}); } catch(e){next(e);} });

router.post('/chat', async (req: AuthRequest,res: Response,next: NextFunction)=>{ try {
  const message=requireText(req.body.message,'message'); const language=typeof req.body.language==='string'?req.body.language:'en'; let convId=req.body.conversationId as string|undefined;
  if(!convId){ const {data,error}=await supabase.from('ai_conversations').insert({farmer_id:req.user!.id,title:`${message.substring(0,30)}...`,language}).select().single(); if(error) throw error; convId=data.id; }
  else { const {data,error}=await supabase.from('ai_conversations').select('id').eq('id',convId).eq('farmer_id',req.user!.id).single(); if(error||!data) throw createApiError(404,'Conversation not found'); await supabase.from('ai_conversations').update({updated_at:new Date().toISOString()}).eq('id',convId).eq('farmer_id',req.user!.id); }
  await supabase.from('ai_messages').insert({conversation_id:convId,farmer_id:req.user!.id,role:'user',content:message});
  const {data:farmerData}=await supabase.from('farmers').select('*').eq('id',req.user!.id).single(); const rag=await searchKnowledge(message,0.7,3); const context=rag.map(r=>`[Source: ${r.ai_documents.title}]\n${r.chunk_text}`).join('\n\n'); const sources=rag.map(r=>({title:r.ai_documents.title,source:r.ai_documents.source,url:r.ai_documents.source_url}));
  const text=await generateGroundedResponse({prompt:message,context,language,farmerContext:farmerData}); const finalResponse={text,sources:sources.length?sources:null}; const {data:msg,error}=await supabase.from('ai_messages').insert({conversation_id:convId,farmer_id:req.user!.id,role:'assistant',content:JSON.stringify(finalResponse)}).select().single(); if(error) throw error;
  res.json({success:true,data:{message:toCamel(msg),conversationId:convId,sources}});
} catch(e){next(e);} });

router.post('/voice', async (req: AuthRequest,res: Response,next: NextFunction)=>{ try { const audio=requireText(req.body.audioBase64,'audioBase64'); const input=parseDataUrl(audio); const language=typeof req.body.language==='string'?req.body.language:'en'; const stt=await transcribeAudio({data:input.data,mimeType:req.body.mimeType||input.mimeType},language); const rag=await searchKnowledge(stt.transcript,0.7,3); const context=rag.map(r=>`[Source: ${r.ai_documents.title}]\n${r.chunk_text}`).join('\n\n'); const response=await generateGroundedResponse({prompt:stt.transcript,context,language:stt.language||language}); res.json({success:true,data:{transcript:stt.transcript,detectedLanguage:stt.language,transcriptionConfidence:stt.confidence,response,sources:rag.map(r=>({title:r.ai_documents.title,source:r.ai_documents.source,url:r.ai_documents.source_url}))}}); } catch(e){next(e);} });

router.post('/disease-detect', async (req: AuthRequest,res: Response,next: NextFunction)=>{ try { const image=requireText(req.body.imageBase64,'imageBase64'); const input=parseDataUrl(image); const result=await detectCropDisease(input.data,typeof req.body.cropName==='string'?req.body.cropName:undefined); const confidence=typeof (result as any).confidence==='number'?(result as any).confidence:0; const disease=typeof (result as any).disease==='string'?(result as any).disease:'Unable to detect'; const healthStatus=disease.toLowerCase()==='healthy'?'healthy':confidence===0?'unknown':'infected'; const {data:report,error}=await supabase.from('ai_image_reports').insert({farmer_id:req.user!.id,image_url:req.body.imageUrl||null,detected_crop:req.body.cropName||null,health_status:healthStatus,diseases:[{name:disease,confidence}],treatment_suggestions:(result as any).treatment||[],prevention_measures:(result as any).prevention||[],confidence_score:confidence}).select().single(); if(error) throw error; res.json({success:true,data:{result,report:toCamel(report)}}); } catch(e){next(e);} });

router.get('/image-reports', async (req: AuthRequest,res: Response,next: NextFunction)=>{ try { const {data,error}=await supabase.from('ai_image_reports').select('*').eq('farmer_id',req.user!.id).order('created_at',{ascending:false}); if(error) throw error; res.json({success:true,data:{reports:toCamel(data)}}); } catch(e){next(e);} });
router.post('/image', async (req: AuthRequest,res: Response,next: NextFunction)=>{ try { const image=requireText(req.body.imageBase64,'imageBase64'); const result=await detectCropDisease(parseDataUrl(image).data,typeof req.body.cropType==='string'?req.body.cropType:undefined); res.json({success:true,data:{report:result}}); } catch(e){next(e);} });

router.post('/document/ocr', async (req: AuthRequest,res: Response,next: NextFunction)=>{ try { const doc=requireText(req.body.documentBase64,'documentBase64'); const input=parseDataUrl(doc); const type=typeof req.body.documentType==='string'?req.body.documentType:'unknown'; const result=await analyzeDocument({data:input.data,mimeType:req.body.mimeType||input.mimeType},type); const {data:stored,error}=await supabase.from('ai_ocr_documents').insert({farmer_id:req.user!.id,document_url:req.body.documentUrl||'inline-upload',document_type:result.documentType||type,extracted_data:result,confidence_score:result.confidence,status:result.needsManualReview?'needs_review':'completed'}).select().single(); if(error) throw error; res.json({success:true,data:{document:toCamel(stored),extraction:result}}); } catch(e){next(e);} });

router.post('/knowledge/ingest', async (req: AuthRequest,res: Response,next: NextFunction)=>{ try { if(!['ADMIN','SUPER_ADMIN'].includes((req.user?.role||'').toUpperCase())) throw createApiError(403,'Admins only'); const title=requireText(req.body.title,'title'); const content=requireText(req.body.content,'content'); const id=await ingestDocument({title,description:req.body.description,source:req.body.source,source_url:req.body.sourceUrl,category:req.body.category,language:req.body.language||'en',content}); res.json({success:true,data:{documentId:id}}); } catch(e){next(e);} });
router.get('/knowledge/search', async (req: AuthRequest,res: Response,next: NextFunction)=>{ try { const q=typeof req.query.q==='string'?req.query.q.trim():''; if(!q) throw createApiError(400,'Query parameter "q" is required'); res.json({success:true,data:{results:await searchKnowledge(q,0.7,5),query:q}}); } catch(e){next(e);} });
router.post('/translate', async (req: AuthRequest,res: Response,next: NextFunction)=>{ try { const text=requireText(req.body.text,'text'); const targetLang=requireText(req.body.targetLang,'targetLang'); const sourceLang=typeof req.body.sourceLang==='string'?req.body.sourceLang:'auto'; res.json({success:true,data:await translateText(text,targetLang,sourceLang)}); } catch(e){next(e);} });
router.get('/analytics', async (req: AuthRequest,res: Response,next: NextFunction)=>{ try { const {data,error}=await supabase.from('ai_analytics').select('*').order('date',{ascending:false}).limit(30); if(error) throw error; const rows=data||[]; const sum=(k:keyof typeof rows[number])=>rows.reduce((n,r)=>n+Number(r[k]||0),0); res.json({success:true,data:{totalConversations:sum('total_conversations'),activeUsers:Math.max(0,...rows.map(r=>Number(r.active_users||0))),voiceRequests:sum('voice_requests'),imageDiagnoses:sum('image_diagnoses'),ocrRequests:sum('ocr_requests'),averageResponseTimeMs:rows.length?Math.round(rows.reduce((n,r)=>n+Number(r.average_response_time_ms||0),0)/rows.length):0,avgAccuracyScore:rows.length?Number((rows.reduce((n,r)=>n+Number(r.avg_accuracy_score||0),0)/rows.length).toFixed(2)):null}}); } catch(e){next(e);} });
export default router;
